version: '3.3'

services:
  db:
    image: mysql:latest
    container_name: nodejs-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - nodejs:/var/lib/mysql
    networks:
      - mynet

  app:
    image: destiaeka/nodejs:latest
    container_name: nodejs-app
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: testdb
    networks:
      - mynet

volumes:
  nodejs:

networks:
  mynet:
