name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub #dockerhub credentials
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image #build & push image ke dockerhub
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-mysql-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-mysql-app:latest    

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: configure database 
      uses: appleboy/ssh-action@v1 #ini pake ssh soal e ambil image dari dockerhub
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2112
        script: |
          git config --global --add safe.directory /var/www/nodejs-application
          cd /var/www/docker/nodejs-application
          docker-compose pull 
          docker-compose up -d --build    
          docker exec nodejs-db mysql -uuser -ppassword -e "use testdb; insert into users(id,nama,alamat) values (01,'destia','sleman')";

